In [1]:
%reset -f

GEMs Files available at [vmh.life](https://www.vmh.life/files/reconstructions/AGORA2/version2.01/mat_files/individual_reconstructions/) or directly:

[AGORA 2 Files - Eubacterium hallii DSM 3353](https://www.vmh.life/files/reconstructions/AGORA2/version2.01/mat_files/individual_reconstructions/Eubacterium_hallii_DSM_3353.mat) 

[AGORA 2 Files - Bifidobacterium longum infantis ATCC 15697](https://www.vmh.life/files/reconstructions/AGORA2/version2.01/mat_files/individual_reconstructions/Bifidobacterium_longum_infantis_ATCC_15697.mat)

# FIND MEDIA FOR FIRST MODEL (LACTATE PRODUCER)

In [2]:
import cobra as cb

In [3]:
# AGORA Format
base_media = {
    'EX_o2(e)': 0, #aerobic/anaerobic
    'EX_h2o(e)': 1000,
    'EX_pi(e)': 1000,
    'EX_fe2(e)': 1000,
    'EX_fe3(e)': 1000,
    'EX_zn2(e)': 1000,
    'EX_so4(e)': 1000,
    'EX_cu2(e)': 1000,
    'EX_k(e)': 1000,
    'EX_mg2(e)': 1000,
    'EX_mn2(e)': 1000,
    'EX_cd2(e)': 1000,
    'EX_cl(e)': 1000,
    'EX_ca2(e)': 1000,
    'EX_cobalt2(e)': 1000,
    'EX_glc_D(e)': 10, # glucose limited
    'EX_nh4(e)': 20,

    'EX_ribflv(e)': 1000,
    'EX_pnto_R(e)': 1000,
    'EX_nac(e)':1000,
    'EX_his_L(e)':1000,
    'EX_asn_L(e)':1000,
    'EX_glycys(e)': 1000,
    #'EX_ac(e)': 10,
}

In [4]:
# Load model
model = cb.io.load_matlab_model('Bifidobacterium_longum_infantis_ATCC_15697.mat')

Set parameter WLSAccessID
Set parameter WLSSecret
Set parameter LicenseID to value 2773320
Academic license 2773320 - for non-commercial use only - registered to rd___@uvm.edu

No defined compartments in model model. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e

In [5]:
# Find minimal media with specific components always added
with model as model_t:
    for rxn_id, uptake in base_media.items():
        met = list(model_t.exchanges.get_by_id(rxn_id).metabolites.keys())[0]
        model_t.add_boundary(met, type="sink", reaction_id=rxn_id+'_tmp',lb=-1*uptake,ub=1000)
        
    for ex in model_t.exchanges:
        ex.lower_bound = -1000
        ex.upper_bound = 1000

    mm = cb.medium.minimal_medium(model_t,0.1,minimize_components=10)

In [6]:
mm

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Index: []

In [7]:
for exchange in model.exchanges:
    if exchange.id in base_media:
        exchange.lower_bound = -1 * base_media[exchange.id]
    else:
        exchange.lower_bound = 0

sol = model.optimize()

In [8]:
model.summary()

In [9]:
%reset -f

# FIND MEDIA FOR SECOND MODEL BUILDING OFF FIRST MODEL (BUTYRATE PRODUCER)

In [1]:
import cobra as cb

In [9]:
# AGORA Format
base_media = {
    'EX_o2(e)': 0, #aerobic/anaerobic
    'EX_h2o(e)': 1000,
    'EX_pi(e)': 1000,
    'EX_fe2(e)': 1000,
    'EX_fe3(e)': 1000,
    'EX_zn2(e)': 1000,
    'EX_so4(e)': 1000,
    'EX_cu2(e)': 1000,
    'EX_k(e)': 1000,
    'EX_mg2(e)': 1000,
    'EX_mn2(e)': 1000,
    'EX_cd2(e)': 1000,
    'EX_cl(e)': 1000,
    'EX_ca2(e)': 1000,
    'EX_cobalt2(e)': 1000,
    'EX_glc_D(e)': 10, # glucose limited
    'EX_nh4(e)': 20,

    'EX_ribflv(e)': 1000,
    'EX_pnto_R(e)': 1000,
    'EX_nac(e)':1000,
    'EX_his_L(e)':1000,
    'EX_asn_L(e)':1000,
    'EX_glycys(e)': 1000,

    'EX_lac_L(e)': 10,

    'EX_lys_L(e)': 1000,
    'EX_ala_L(e)': 1000,
    'EX_met_L(e)': 1000,
    'EX_leu_L(e)': 1000,
    'EX_hxan(e)': 1000,    
    #'EX_ser_L(e)': 1000,
    'EX_glyasn(e)': 1000
}

In [10]:
# Load model
model = cb.io.load_matlab_model('Eubacterium_hallii_DSM_3353.mat')

No defined compartments in model model. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e

In [11]:
# Find minimal media with specific components always added
with model as model_t:
    for rxn_id, uptake in base_media.items():
        if rxn_id in model_t.exchanges:
            met = list(model_t.exchanges.get_by_id(rxn_id).metabolites.keys())[0]
            model_t.add_boundary(met, type="sink", reaction_id=rxn_id+'_tmp',lb=-1*uptake,ub=1000)
        else:
            print(rxn_id)
        
    for ex in model_t.exchanges:
        ex.lower_bound = -1000
        ex.upper_bound = 1000

    mm = cb.medium.minimal_medium(model_t,0.1,minimize_components=10)

In [12]:
mm

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Index: []

In [13]:
for exchange in model.exchanges:
    if exchange.id in base_media:
        exchange.lower_bound = -1 * base_media[exchange.id]
    else:
        exchange.lower_bound = 0

sol = model.optimize()

In [14]:
model.summary()

In [17]:
%reset -f

# RE-RUN FIRST MODEL WITH COMBINED MEDIA

In [15]:
import cobra as cb

In [16]:
# AGORA Format
base_media = {
    'EX_o2(e)': 0, #aerobic/anaerobic
    'EX_h2o(e)': 1000,
    'EX_pi(e)': 1000,
    'EX_fe2(e)': 1000,
    'EX_fe3(e)': 1000,
    'EX_zn2(e)': 1000,
    'EX_so4(e)': 1000,
    'EX_cu2(e)': 1000,
    'EX_k(e)': 1000,
    'EX_mg2(e)': 1000,
    'EX_mn2(e)': 1000,
    'EX_cd2(e)': 1000,
    'EX_cl(e)': 1000,
    'EX_ca2(e)': 1000,
    'EX_cobalt2(e)': 1000,
    'EX_glc_D(e)': 10, # glucose limited
    'EX_nh4(e)': 20,

    'EX_ribflv(e)': 1000,
    'EX_pnto_R(e)': 1000,
    'EX_nac(e)':1000,
    'EX_his_L(e)':1000,
    'EX_asn_L(e)':1000,
    'EX_glycys(e)': 1000,

    'EX_lac_L(e)': 10,

    'EX_lys_L(e)': 1000,
    'EX_ala_L(e)': 1000,
    'EX_met_L(e)': 1000,
    'EX_leu_L(e)': 1000,
    'EX_hxan(e)': 1000,    
    'EX_ser_L(e)': 1,
}

In [17]:
# Load model
model = cb.io.load_matlab_model('Bifidobacterium_longum_infantis_ATCC_15697.mat')

No defined compartments in model model. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e

In [18]:
for exchange in model.exchanges:
    if exchange.id in base_media:
        exchange.lower_bound = -1 * base_media[exchange.id]
    else:
        exchange.lower_bound = 0

sol = model.optimize()
model.summary()